#! /bin/sh

# windows gap
bspc config window_gap 20;

#Various settings
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  false
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false
bspc config single_monocle true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#bspwm rules
#bspc rule -a Termite:termite state=pseudo_tiled

##Color settings
bspc config focused_border_color "#30c0a5"
bspc config normal_border_color "#282a36"
bspc config presel_feedback_color "#3b3d4a"
bspc config border_width 3

#Settings for manual splitting
bspc config split_ratio   0.50

bspc monitor -d 1 2 3 4 5

#Keybindings daemon
killall sxhkd ; sxhkd &

# compton compositor
killall compton; compton&

# panel -- Polybar
killall polybar ; polybar mybar &

# wallpaper
feh --bg-fill ~/Wallpaper/wallpaper.jpg

# load xresourses
xrdb .Xresources

# load theme cursor
xsetroot -cursor_name left_ptr

# clipboard manager 
killall python2; anamnesis --start

# Notification system
killall dunst ; dunst &

# Battery tracker
killall batteryTracker; batteryTracker &

# night light 
killall redshift ; redshift &
