#! /bin/sh

# windows gap
bspc config window_gap 0;

#Various settings
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  false
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false
bspc config single_monocle true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

##Color settings
bspc config focused_border_color "#4c566a"
bspc config normal_border_color "#21252d"
bspc config presel_feedback_color "#30ab96"
bspc config border_width 2

#Settings for manual splitting
bspc config split_ratio   0.50

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Keybindings daemon
killall sxhkd ; sxhkd &

# compton compositor
#killall compton 2>&1 > /dev/null; compton&

# panel -- Polybar
killall polybar 2>&1 > /dev/null; polybar mybar &

# redshift
#killall redshift ; redshift &

# wallpaper
feh --bg-fill ~/Wallpaper/wallpaper.png

# load xresourses
xrdb .Xresources

# load theme cursor
xsetroot -cursor_name left_ptr

# Notification system
killall dunst 2>&1 > /dev/null; dunst &

# Battery tracker
killall batteryTracker 2>&1 > /dev/null; batteryTracker &

#sleep 10
#xrandr --output eDP --brightness 0.0

killall polkit-mate-aut; /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
